apiVersion: 1

datasources:
  - name: Sentinel Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: sentinel-prometheus
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
  - name: Sentinel Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: sentinel-loki
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
